apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sresource
  namespace: default
  labels:
    app: sresource
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - sresource.example.com
    secretName: sresource-tls
  rules:
  - host: sresource.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sresource
            port:
              number: 80